pretrain: /mnt/data3/jawu/haichen/workspace/BiEfficient/k400-vit-l-14-336-f16.pt
resume:
seed: 1024
data:
    dataset: hmdb51
    modality: RGB
    num_segments: 16
    seg_length: 1
    batch_size: 12
    workers: 4
    num_classes: 51
    image_tmpl: 'img_{:05d}.jpg'
    train_root: '/mnt/data3/jawu/haichen/datasets/hmdb51/rawframes'
    val_root: '/mnt/data3/jawu/haichen/datasets/hmdb51/rawframes'
    train_list: 'lists/hmdb51/train_rgb_split_1.txt'
    val_list: 'lists/hmdb51/val_rgb_split_1.txt'
    label_list: 'lists/hmdb51/hmdb51_labels.csv'
    input_size: 336
    random_shift: True
    output_path: exps
network:
    arch: ViT-L/14-336px
    init: True
    tm: False
    drop_out: 0.0 
    emb_dropout: 0.0
    sim_header: Transf
    interaction: VCS
    joint_st: False
    drop: 0      
    fix_text: True  
    fix_video: False      
solver:
    type: cosine
    epochs: 20
    start_epoch: 0
    optim: adamw
    lr: 5.e-5
    lr_warmup_step: 5
    weight_decay: 0.2
    loss_type: NCE
    evaluate: False
    clip_ratio: 0.1
    grad_accumulation_steps: 1
logging:
    print_freq: 10
    eval_freq: 2