resume: 
pretrain:
seed: 1024
data:
    dataset: k400
    modality: video
    num_segments: 8
    seg_length: 1
    batch_size: 32
    workers: 8
    num_classes: 400
    image_tmpl: 'img_{:05d}.jpg'
    train_root: '/root/autodl-tmp/datasets/kinetics400/video_train'
    train_list: '/root/autodl-tmp/datasets/kinetics400/datalist/kinetics_video_train.txt'
    val_root: '/root/autodl-tmp/datasets/kinetics400/video_val'
    val_list: '/root/autodl-tmp/datasets/kinetics400/datalist/kinetics_video_val.txt'
    label_list: '/root/autodl-tmp/datasets/kinetics400/labels.csv'
    input_size: 224
    random_shift: True
    output_path: exps
    temporal_clip: 3
    spatial_crop: 1
    num_prompt: 12
network:
    arch: ViT-B/16  #ViT-B/32 ViT-B/16
    patch_size: 16
    init: True
    tm: False
    drop_out: 0.0
    emb_dropout: 0.0 
    sim_header: Transf  # Transf   None  
    interaction: VCS  # DP VCS
    joint_st: True
    drop: 0           
solver:
    type: cosine
    epochs: 50
    start_epoch: 0
    epoch_offset: 0
    optim: adamw
    lr: 5.e-4
    lr_warmup_step: 5
    weight_decay: 0.05 
    # loss_type: NCE
    evaluate: False
    clip_ratio: 0.1
    grad_accumulation_steps: 1
logging:
    print_freq: 10
    eval_freq: 1